[settings]
environment = "dev"
show_compiler_warnings = true 

[codegen]
structs_dir = "src/structs/generated"
models_dir = "src/models/generated"
schema_file = "src/database/schema.rs"

[codegen.models]
ignore= [
  "users"
]

[codegen.structs]
ignored_structs = [
  "users"
]
derives = [
  "Debug",
  "Queryable",
  "Clone", 
  "Serialize", 
  "Deserialize"
]
imports = [
  "serde::Serialize",
  "serde::Deserialize",
  "diesel::Queryable"
]

[assets]
public_dir = "public"

[assets.locale]
dir = "src/assets/locale"
default_language = "en"

[assets.materialize]
js_url = "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"
public_dir = "materialize"

[assets.materialicons]
base_url = "https://raw.githubusercontent.com/google/material-design-icons/master/font"
public_dir = "fonts/material-icons"
woff2 = "MaterialIcons-Regular.woff2"
ttf = "MaterialIcons-Regular.ttf"

[assets.fontawesome]
base_url = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/latest"
public_dir = "fonts/fontawesome"
css = ["css/all.min.css"]
js = ["js/all.min.js"]
sprites = ["sprites/brands.svg", "sprites/regular.svg", "sprites/solid.svg"]
webfonts = [
  "webfonts/fa-brands-400.ttf",
  "webfonts/fa-brands-400.woff2",
  "webfonts/fa-regular-400.ttf",
  "webfonts/fa-regular-400.woff2",
  "webfonts/fa-solid-900.ttf",
  "webfonts/fa-solid-900.woff2",
  "webfonts/fa-v4compatibility.ttf",
  "webfonts/fa-v4compatibility.woff2"
]


