//! Pure emitter for the icons.ts registry. Takes an `IconConfig` and
//! produces the TypeScript body — no I/O, no header marker. The runner
//! prepends the marker.

use crate::state::IconConfig;

/// Render the `icons.ts` body. Iteration order is deterministic via the
/// underlying `BTreeMap`, which is ordered by `IconKey`.
///
/// Output shape: a TS object literal named `IC` with one `key: 'class'`
/// entry per registered icon, then `as const` so the literal narrows to
/// its specific keys. After the literal we export `IconName` as the
/// exact union of those keys via `keyof typeof IC`.
///
/// The `as const` is mandatory — it makes `IconName` an exact union of
/// registry keys, not the open `string` type. Key column is right-padded
/// so values land at a consistent column for the longest key in the
/// registry, matching the alignment style of the original static body.
pub fn emit_icons_ts(cfg: &IconConfig) -> String {
    let mut out = String::new();
    out.push_str("export const IC = {\n");
    let entries: Vec<(&crate::state::IconKey, &crate::state::IconClass)> =
        cfg.registry.iter().collect();
    let last_idx = entries.len().saturating_sub(1);
    let key_pad = longest_key(&entries);
    for (i, (key, class)) in entries.iter().enumerate() {
        let comma = if i == last_idx { "" } else { "," };
        let key_str = key.as_str();
        let pad_len = key_pad - key_str.len() + 1;
        let pad = " ".repeat(pad_len);
        out.push_str(&format!(
            "  {}:{}'{}'{}\n",
            key_str,
            pad,
            class.as_str(),
            comma,
        ));
    }
    out.push_str("} as const\n");
    out.push('\n');
    out.push_str("export type IconName = keyof typeof IC\n");
    out
}

fn longest_key(entries: &[(&crate::state::IconKey, &crate::state::IconClass)]) -> usize {
    let mut max = 0usize;
    for (key, _) in entries {
        let len = key.as_str().len();
        if len > max {
            max = len;
        }
    }
    max
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::{IconClass, IconConfig, IconKey};
    use std::collections::BTreeMap;

    /// Static reference body — copy of the current ICONS_TS_BODY constant
    /// in `src/codegen/fe_runtime_extras.rs`. Used to assert the (key →
    /// class) entry set matches.
    const REFERENCE_ICONS_TS: &str = r#"// Icon registry. Generated by Blast as a SEED — extend freely.
// Governor's IconClassOutsideIconsFile rule means literal "pi-foo" / "ph-foo"
// strings only live here; components import IC.<name> instead.
export const IC = {
  // Navigation / common
  home:       'pi pi-home',
  dashboard:  'pi pi-th-large',
  settings:   'pi pi-cog',
  cog:        'pi pi-cog',
  user:       'pi pi-user',
  users:      'pi pi-users',
  tools:      'pi pi-wrench',
  // Actions
  add:        'pi pi-plus',
  edit:       'pi pi-pencil',
  delete:     'pi pi-trash',
  save:       'pi pi-check',
  cancel:     'pi pi-times',
  back:       'pi pi-arrow-left',
  // Status
  warning:    'pi pi-exclamation-triangle',
  error:      'pi pi-times-circle',
  success:    'pi pi-check-circle',
  info:       'pi pi-info-circle',
  // Data
  search:     'pi pi-search',
  filter:     'pi pi-filter',
  sort:       'pi pi-sort',
  refresh:    'pi pi-refresh',
} as const;

export type IconName = keyof typeof IC;
"#;

    /// Parse a TS-shaped IC registry body into a (key → class) map.
    /// Lines look like `  home:       'pi pi-home',` — the comma is
    /// optional on the final line and the leading whitespace varies. We
    /// strip both, locate the first colon, and split at the surrounding
    /// single-quotes for the class.
    fn parse_ic_entries(ts_body: &str) -> BTreeMap<String, String> {
        let mut out = BTreeMap::new();
        for line in ts_body.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with("//") {
                continue;
            }
            if !trimmed.contains(':') || !trimmed.contains('\'') {
                continue;
            }
            // Skip the `} as const` and `export const IC` and similar lines.
            let starts_with_lower = trimmed
                .chars()
                .next()
                .map(|c| c.is_ascii_lowercase())
                .unwrap_or(false);
            if !starts_with_lower {
                continue;
            }
            let colon = match trimmed.find(':') {
                Some(i) => i,
                None => continue,
            };
            let name = trimmed[..colon].trim().to_string();
            let after_colon = &trimmed[colon + 1..];
            let q1 = match after_colon.find('\'') {
                Some(i) => i,
                None => continue,
            };
            let rest = &after_colon[q1 + 1..];
            let q2 = match rest.find('\'') {
                Some(i) => i,
                None => continue,
            };
            let class = rest[..q2].to_string();
            out.insert(name, class);
        }
        out
    }

    #[test]
    fn emits_const_ic_block_and_type_alias() {
        let body = emit_icons_ts(&IconConfig::default());
        assert!(body.contains("export const IC = {"));
        assert!(body.contains("} as const"));
        assert!(body.contains("export type IconName = keyof typeof IC"));
    }

    #[test]
    fn emits_all_default_entries() {
        let body = emit_icons_ts(&IconConfig::default());
        let expected = [
            ("home", "pi pi-home"),
            ("dashboard", "pi pi-th-large"),
            ("settings", "pi pi-cog"),
            ("cog", "pi pi-cog"),
            ("user", "pi pi-user"),
            ("users", "pi pi-users"),
            ("tools", "pi pi-wrench"),
            ("add", "pi pi-plus"),
            ("edit", "pi pi-pencil"),
            ("delete", "pi pi-trash"),
            ("save", "pi pi-check"),
            ("cancel", "pi pi-times"),
            ("back", "pi pi-arrow-left"),
            ("warning", "pi pi-exclamation-triangle"),
            ("error", "pi pi-times-circle"),
            ("success", "pi pi-check-circle"),
            ("info", "pi pi-info-circle"),
            ("search", "pi pi-search"),
            ("filter", "pi pi-filter"),
            ("sort", "pi pi-sort"),
            ("refresh", "pi pi-refresh"),
        ];
        for (k, v) in expected {
            let needle = format!("'{}'", v);
            assert!(
                body.contains(&needle),
                "expected emitted body to contain {needle}"
            );
            assert!(body.contains(k), "expected emitted body to contain key {k}");
        }
    }

    #[test]
    fn entry_set_matches_static_reference() {
        let emitted = emit_icons_ts(&IconConfig::default());
        let lhs = parse_ic_entries(&emitted);
        let rhs = parse_ic_entries(REFERENCE_ICONS_TS);
        assert_eq!(
            lhs, rhs,
            "icons.ts entry set drifted from static reference\nlhs: {lhs:#?}\nrhs: {rhs:#?}"
        );
    }

    #[test]
    fn entry_count_pinned_at_21() {
        let body = emit_icons_ts(&IconConfig::default());
        let entries = parse_ic_entries(&body);
        assert_eq!(entries.len(), 21);
    }

    #[test]
    fn empty_registry_produces_well_formed_output() {
        let cfg = IconConfig {
            registry: BTreeMap::new(),
        };
        let body = emit_icons_ts(&cfg);
        assert!(body.contains("export const IC = {\n} as const"));
        assert!(body.contains("export type IconName = keyof typeof IC"));
    }

    #[test]
    fn single_entry_has_no_trailing_comma() {
        let mut registry = BTreeMap::new();
        registry.insert(
            IconKey::new("home").unwrap(),
            IconClass::new("pi pi-home").unwrap(),
        );
        let body = emit_icons_ts(&IconConfig { registry });
        assert!(body.contains("  home: 'pi pi-home'\n} as const"));
    }
}
