use std::path::{Path, PathBuf};

pub const LAYERS_WITH_GENERATED_AND_CUSTOM: &[&str] = &[
    "structs",
    "models",
    "services",
    "routines",
    "flows",
    "routes",
];

pub const TRANSPORT_SUBLAYERS: &[&str] = &["http", "ws", "fuses"];

pub fn cargo_toml(project_name: &str, catalyst_dep_line: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
{catalyst_dep}
axum = {{ version = "0.7", features = ["json", "macros", "ws"] }}
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
diesel = {{ version = "2.2", features = ["postgres", "64-column-tables", "chrono", "serde_json", "r2d2"] }}
diesel_migrations = {{ version = "2.2", features = ["postgres"] }}
chrono = {{ version = "0.4", features = ["serde"] }}
dotenv = "0.15"
tracing = "0.1"
thiserror = "1"

[build-dependencies]
blake3 = "1.5"

[profile.dev]
codegen-units = 12
opt-level = 0
lto = false
debug = true

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"
debug = false
"#,
        name = project_name,
        catalyst_dep = catalyst_dep_line,
    )
}

pub fn catalyst_path_dep(catalyst_relative: &str) -> String {
    format!(
        r#"catalyst = {{ path = "{}", features = ["testing"] }}"#,
        catalyst_relative
    )
}

pub fn catalyst_git_dep() -> String {
    r#"catalyst = { git = "https://github.com/Arete-Innovations/catalyst", branch = "main", features = ["testing"] }"#.to_string()
}

pub fn gitignore() -> &'static str {
    "/target/\n\
     **/*.rs.bk\n\
     Cargo.lock\n\
     \n\
     .env\n\
     \n\
     /storage/logs/*.log\n\
     /storage/blast/server.pid\n\
     \n\
     .idea/\n\
     .vscode/\n\
     *.iml\n\
     \n\
     /frontend/node_modules/\n\
     /frontend/dist/\n\
     /public/static/assets/\n"
}

pub fn env_example(project_name: &str) -> String {
    format!(
        "DATABASE_URL=postgres://postgres:postgres@localhost/{name}\n\
         BLAST_ENV=dev\n\
         RUST_LOG=info\n",
        name = project_name,
    )
}

pub fn main_rs() -> &'static str {
    r#"use catalyst::bootstrap::bootstrap;
use catalyst::cata_log;

mod structs;
mod models;
mod services;
mod routines;
mod flows;
mod routes;
mod transport;
mod database;

#[tokio::main]
async fn main() {
    catalyst::logger::init_tracing();
    bootstrap().await;
    cata_log!(Info, "App entrypoint reached. Wire your routes/flows here.");
}
"#
}

pub fn layer_mod_rs() -> &'static str {
    "pub mod generated;\npub mod custom;\n"
}

pub fn empty_layer_inner_mod_rs() -> &'static str {
    "// generated by `blast gen all`. do not hand-edit.\n"
}

pub fn empty_custom_mod_rs() -> &'static str {
    "// custom code lives here. blast never overwrites this directory.\n"
}

pub fn transport_mod_rs() -> &'static str {
    "pub mod http;\npub mod ws;\npub mod fuses;\n"
}

pub fn database_mod_rs() -> &'static str {
    "pub mod schema;\n"
}

pub fn database_schema_rs() -> &'static str {
    "// AUTO-GENERATED by Diesel. run `diesel migration run` to refresh.\n\
     // empty until first migration runs.\n"
}

pub fn frontend_package_json(project_name: &str) -> String {
    format!(
        r#"{{
  "name": "{name}-frontend",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "vue": "^3.4.0",
    "vue-router": "^4.4.0",
    "primevue": "^4.0.0",
    "@primevue/themes": "^4.0.0"
  }},
  "devDependencies": {{
    "@vitejs/plugin-vue": "^5.0.0",
    "typescript": "^5.4.0",
    "vite": "^5.2.0",
    "vue-tsc": "^2.0.0"
  }}
}}
"#,
        name = project_name,
    )
}

// frontend index.html is owned by codegen::fe_runtime; the runtime
// scaffold step seeds it (with app-name substitution) on `blast new`
// and re-asserts it as write-if-absent on `blast gen all`.

pub fn frontend_vite_config_ts() -> &'static str {
    r#"import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  server: {
    port: 5173,
    strictPort: true,
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
})
"#
}

// frontend src/main.ts is owned by codegen::fe_runtime; it installs
// vue-router on top of PrimeVue and lives as write-if-absent so the
// user can extend it after first emission.

pub fn frontend_app_vue() -> &'static str {
    r#"<script setup lang="ts">
import { Suspense } from 'vue'

import GlobalProgressBar from '@/components/GlobalProgressBar.vue'
</script>

<template>
  <GlobalProgressBar />
  <Suspense>
    <RouterView />
  </Suspense>
</template>

<style scoped>
@layer app {
  /* App.vue stays empty — pages own layout via PageShell. */
}
</style>
"#
}

pub fn frontend_tsconfig_json() -> &'static str {
    r#"{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue"]
}
"#
}

pub fn storage_blast_gitignore() -> &'static str {
    "logs/\nserver.pid\nrun-locks/\n"
}

pub fn migrations_keep_marker() -> &'static str {
    "# diesel migrations live here.\n# create one with: blast gen migration --custom <name>\n"
}

pub fn gitkeep_marker() -> &'static str {
    "# directory placeholder. blast populates or replaces this.\n"
}

pub struct LayerPaths {
    pub mod_path: PathBuf,
    pub generated_mod: PathBuf,
    pub custom_mod: PathBuf,
}

pub fn layer_paths(src_root: &Path, layer: &str) -> LayerPaths {
    let layer_dir = src_root.join(layer);
    LayerPaths {
        mod_path: layer_dir.join("mod.rs"),
        generated_mod: layer_dir.join("generated").join("mod.rs"),
        custom_mod: layer_dir.join("custom").join("mod.rs"),
    }
}

pub struct TransportSublayerPaths {
    pub mod_path: PathBuf,
    pub generated_mod: PathBuf,
    pub custom_mod: PathBuf,
}

pub fn transport_sublayer_paths(src_root: &Path, sub: &str) -> TransportSublayerPaths {
    let sub_dir = src_root.join("transport").join(sub);
    TransportSublayerPaths {
        mod_path: sub_dir.join("mod.rs"),
        generated_mod: sub_dir.join("generated").join("mod.rs"),
        custom_mod: sub_dir.join("custom").join("mod.rs"),
    }
}
