//! FE runtime extras emitted alongside the routing/blocking-nav scaffold.
//!
//! Split out from `fe_runtime.rs` so each file stays under the build.rs
//! decomposition cap. These two files are the only "framework primitives"
//! every app needs but that aren't routing-specific:
//!   - `icons.ts` — icon registry honoring Governor's IconClassOutsideIconsFile rule
//!   - `generated/bus.ts` — singleton typed event bus that replaces Pinia for
//!     cross-resource event coordination
//!
//! Lane 8 ships these as `write_if_absent` seeds; lane 1's `fe_runtime::run`
//! consumes the constants here when building the scaffold target list.

pub const ICONS_TS: &str = ICONS_TS_BODY;
pub const BUS_TS: &str = BUS_TS_BODY;

const ICONS_TS_BODY: &str = r#"// Icon registry. Generated by Blast as a SEED — extend freely.
// Governor's IconClassOutsideIconsFile rule means literal "pi-foo" / "ph-foo"
// strings only live here; components import IC.<name> instead.
export const IC = {
  // Navigation / common
  home:       'pi pi-home',
  dashboard:  'pi pi-th-large',
  settings:   'pi pi-cog',
  cog:        'pi pi-cog',
  user:       'pi pi-user',
  users:      'pi pi-users',
  tools:      'pi pi-wrench',
  // Actions
  add:        'pi pi-plus',
  edit:       'pi pi-pencil',
  delete:     'pi pi-trash',
  save:       'pi pi-check',
  cancel:     'pi pi-times',
  back:       'pi pi-arrow-left',
  // Status
  warning:    'pi pi-exclamation-triangle',
  error:      'pi pi-times-circle',
  success:    'pi pi-check-circle',
  info:       'pi pi-info-circle',
  // Data
  search:     'pi pi-search',
  filter:     'pi pi-filter',
  sort:       'pi pi-sort',
  refresh:    'pi pi-refresh',
} as const;

export type IconName = keyof typeof IC;
"#;

const BUS_TS_BODY: &str = r#"// Catablast event bus. Singleton, typed, no Pinia.
// Per-resource typed channels live in @/generated/composables/<resource>.ts
// (emitted alongside mutation hooks).

type Listener<T> = (payload: T) => void;

const channels = new Map<string, Set<Listener<unknown>>>();

export function emit<T>(channel: string, payload: T): void {
  const set = channels.get(channel);
  if (!set) return;
  for (const listener of set) {
    listener(payload as unknown);
  }
}

export function on<T>(channel: string, listener: Listener<T>): () => void {
  let set = channels.get(channel);
  if (!set) {
    set = new Set();
    channels.set(channel, set);
  }
  set.add(listener as Listener<unknown>);
  return () => off(channel, listener);
}

export function off<T>(channel: string, listener: Listener<T>): void {
  const set = channels.get(channel);
  if (!set) return;
  set.delete(listener as Listener<unknown>);
  if (set.size === 0) channels.delete(channel);
}

export function clearAll(): void {
  channels.clear();
}
"#;
