use crate::codegen::ir_loader::{self, FieldSpec, ResourceIr};
use crate::codegen::ts_validator;
use crate::error::BlastResult;
use std::fs;
use std::path::{Path, PathBuf};

const MAX_PAGE_SIZE_WIRE: u32 = 200;
const DEFAULT_PAGE_SIZE_WIRE: u32 = 50;

pub fn run_frontend(project_root: &Path) -> BlastResult<()> {
    let resources = ir_loader::load_primer_ir(project_root)?;
    emit_validators(project_root, &resources)?;
    emit_list_query_module(project_root)?;
    emit_per_resource_list_helpers(project_root, &resources)?;
    Ok(())
}

fn emit_validators(project_root: &Path, resources: &[ResourceIr]) -> BlastResult<()> {
    let out_dir = validators_dir(project_root);
    fs::create_dir_all(&out_dir)?;

    for r in resources {
        let mut body = String::new();
        body.push_str(&format!(
            "// AUTO-GENERATED by blast gen frontend — do not edit.\n// resource: {}\n\n",
            r.table
        ));
        for field in fields_with_validators(&r.fields) {
            body.push_str(&ts_validator::emit_ts(field));
            body.push('\n');
        }
        let file = out_dir.join(format!("{}.ts", r.table));
        fs::write(&file, body)?;
    }

    let mut index = String::new();
    index.push_str("// AUTO-GENERATED by blast gen frontend — do not edit.\n");
    let mut tables: Vec<&str> = resources.iter().map(|r| r.table.as_str()).collect();
    tables.sort();
    for table in tables {
        index.push_str(&format!("export * from './{}'\n", table));
    }
    fs::write(out_dir.join("index.ts"), index)?;

    Ok(())
}

fn fields_with_validators(fields: &[FieldSpec]) -> impl Iterator<Item = &FieldSpec> {
    fields.iter().filter(|f| !f.validation.validators.is_empty())
}

fn validators_dir(project_root: &Path) -> PathBuf {
    project_root
        .join("frontend")
        .join("src")
        .join("generated")
        .join("validators")
}

fn generated_dir(project_root: &Path) -> PathBuf {
    project_root.join("frontend").join("src").join("generated")
}

fn queries_dir(project_root: &Path) -> PathBuf {
    generated_dir(project_root).join("queries")
}

fn emit_list_query_module(project_root: &Path) -> BlastResult<()> {
    let dir = generated_dir(project_root);
    fs::create_dir_all(&dir)?;
    let body = build_list_query_ts();
    fs::write(dir.join("list_query.ts"), body)?;
    Ok(())
}

fn build_list_query_ts() -> String {
    format!(
        "// AUTO-GENERATED by blast gen frontend — do not edit.\n\
//\n\
// Mirrors the wire schema of `catalyst_primer::list_query`. Per-resource\n\
// list helpers (under ./queries/) bake in the primer's filterable /\n\
// sortable column whitelists and `max_page_size` cap.\n\
\n\
export const DEFAULT_PAGE_SIZE = {default_size}\n\
export const MAX_PAGE_SIZE = {max_size}\n\
export const DEFAULT_PAGE = 1\n\
\n\
export interface ListQuery {{\n\
  page: number\n\
  page_size: number\n\
  sort?: string\n\
  filters: Record<string, string>\n\
}}\n\
\n\
export function buildListQuery(q: ListQuery): URLSearchParams {{\n\
  const out = new URLSearchParams()\n\
  out.set('page', String(q.page))\n\
  out.set('page_size', String(q.page_size))\n\
  if (q.sort !== undefined && q.sort !== '') {{\n\
    out.set('sort', q.sort)\n\
  }}\n\
  for (const [col, val] of Object.entries(q.filters)) {{\n\
    out.append(`filter[${{col}}]`, val)\n\
  }}\n\
  return out\n\
}}\n\
\n\
export function parseListQuery(s: string, maxPageSize: number = MAX_PAGE_SIZE): ListQuery {{\n\
  const params = new URLSearchParams(s)\n\
  let page = DEFAULT_PAGE\n\
  let page_size = DEFAULT_PAGE_SIZE\n\
  let sort: string | undefined\n\
  const filters: Record<string, string> = {{}}\n\
\n\
  const rawPage = params.get('page')\n\
  if (rawPage !== null) {{\n\
    const n = Number(rawPage)\n\
    if (Number.isInteger(n) && n >= 1) {{\n\
      page = n\n\
    }}\n\
  }}\n\
\n\
  const rawSize = params.get('page_size')\n\
  if (rawSize !== null) {{\n\
    const n = Number(rawSize)\n\
    if (Number.isInteger(n) && n >= 1) {{\n\
      page_size = Math.min(n, maxPageSize)\n\
    }}\n\
  }}\n\
\n\
  const rawSort = params.get('sort')\n\
  if (rawSort !== null && rawSort !== '') {{\n\
    sort = rawSort\n\
  }}\n\
\n\
  for (const [key, value] of params.entries()) {{\n\
    const m = /^filter\\[(.+)\\]$/.exec(key)\n\
    if (m !== null && m[1].length > 0) {{\n\
      filters[m[1]] = value\n\
    }}\n\
  }}\n\
\n\
  return {{ page, page_size, sort, filters }}\n\
}}\n",
        default_size = DEFAULT_PAGE_SIZE_WIRE,
        max_size = MAX_PAGE_SIZE_WIRE,
    )
}

fn emit_per_resource_list_helpers(
    project_root: &Path,
    resources: &[ResourceIr],
) -> BlastResult<()> {
    let dir = queries_dir(project_root);
    fs::create_dir_all(&dir)?;

    let mut emitted_tables: Vec<&str> = Vec::new();
    for r in resources {
        let Some(verb) = r.list_verb() else {
            continue;
        };
        emitted_tables.push(r.table.as_str());
        let body = build_resource_list_ts(&r.table, verb);
        fs::write(dir.join(format!("{}_list.ts", r.table)), body)?;
    }

    let mut index = String::new();
    index.push_str("// AUTO-GENERATED by blast gen frontend — do not edit.\n");
    emitted_tables.sort();
    for table in emitted_tables {
        index.push_str(&format!("export * from './{}_list'\n", table));
    }
    fs::write(dir.join("index.ts"), index)?;

    Ok(())
}

fn build_resource_list_ts(table: &str, verb: &ir_loader::VerbSpec) -> String {
    let sortable = ts_string_array(&verb.filter.sortable_columns);
    let filterable = ts_string_array(&verb.filter.filterable_columns);
    let default_sort = match &verb.filter.default_sort {
        Some(s) => format!("'{}'", s.replace('\\', "\\\\").replace('\'', "\\'")),
        None => "undefined".to_string(),
    };
    let max_page = match verb.filter.max_page_size {
        Some(v) => v,
        None => MAX_PAGE_SIZE_WIRE,
    };

    format!(
        "// AUTO-GENERATED by blast gen frontend — do not edit.\n\
// resource: {table}\n\
\n\
export const SORTABLE_COLUMNS = {sortable} as const\n\
export const FILTERABLE_COLUMNS = {filterable} as const\n\
export const DEFAULT_SORT: string | undefined = {default_sort}\n\
export const MAX_PAGE_SIZE: number = {max_page}\n\
\n\
export type SortableColumn = typeof SORTABLE_COLUMNS[number]\n\
export type FilterableColumn = typeof FILTERABLE_COLUMNS[number]\n\
\n\
export function isSortable(col: string): col is SortableColumn {{\n\
  return (SORTABLE_COLUMNS as readonly string[]).includes(col)\n\
}}\n\
\n\
export function isFilterable(col: string): col is FilterableColumn {{\n\
  return (FILTERABLE_COLUMNS as readonly string[]).includes(col)\n\
}}\n",
    )
}

fn ts_string_array(values: &[String]) -> String {
    if values.is_empty() {
        return "[]".to_string();
    }
    let parts: Vec<String> = values
        .iter()
        .map(|s| format!("'{}'", s.replace('\\', "\\\\").replace('\'', "\\'")))
        .collect();
    format!("[{}]", parts.join(", "))
}
