use crate::codegen::ir_loader::{self, FieldSpec, ResourceIr};
use crate::codegen::ts_validator;
use crate::error::BlastResult;
use std::fs;
use std::path::{Path, PathBuf};

/// Top-level entry for the frontend codegen pass. Reads primer IR from
/// `target/primer/*.json` and emits TS validators + list query helpers under
/// `frontend/src/generated/`.
pub fn run_frontend(project_root: &Path) -> BlastResult<()> {
    let resources = ir_loader::load_primer_ir(project_root)?;
    emit_validators(project_root, &resources)?;
    Ok(())
}

/// Emit `frontend/src/generated/validators/<resource>.ts` per IR plus a
/// barrel `index.ts` re-exporting every per-resource module. Always
/// rewritten wholesale — Blast owns the `generated/` subtree.
fn emit_validators(project_root: &Path, resources: &[ResourceIr]) -> BlastResult<()> {
    let out_dir = validators_dir(project_root);
    fs::create_dir_all(&out_dir)?;

    for r in resources {
        let mut body = String::new();
        body.push_str(&format!(
            "// AUTO-GENERATED by blast gen frontend — do not edit.\n// resource: {}\n\n",
            r.table
        ));
        for field in fields_with_validators(&r.fields) {
            body.push_str(&ts_validator::emit_ts(field));
            body.push('\n');
        }
        let file = out_dir.join(format!("{}.ts", r.table));
        fs::write(&file, body)?;
    }

    let mut index = String::new();
    index.push_str("// AUTO-GENERATED by blast gen frontend — do not edit.\n");
    let mut tables: Vec<&str> = resources.iter().map(|r| r.table.as_str()).collect();
    tables.sort();
    for table in tables {
        index.push_str(&format!("export * from './{}'\n", table));
    }
    fs::write(out_dir.join("index.ts"), index)?;

    Ok(())
}

fn fields_with_validators(fields: &[FieldSpec]) -> impl Iterator<Item = &FieldSpec> {
    fields.iter().filter(|f| !f.validation.validators.is_empty())
}

fn validators_dir(project_root: &Path) -> PathBuf {
    project_root
        .join("frontend")
        .join("src")
        .join("generated")
        .join("validators")
}
