//! `blast gen governor-plugin` — emits the Vite plugin shim that calls
//! `blast check` on prebuild/predev hooks.
//!
//! The plugin is intentionally a tiny `execSync` bridge — all real lint
//! logic lives in the Rust `governor` module. The user wires the plugin
//! into `vite.config.ts` once; from then on every Vite build invokes the
//! Rust lint engine.
//!
//! Whitelist file emission (`.rule_violations_whitelist`) is deferred until
//! blueprint IR exposes `whitelist_snippet([...])` data — for now an empty
//! whitelist is the implicit default and Governor handles its absence.

use std::fs;
use std::path::{Path, PathBuf};

use crate::error::{BlastError, BlastResult};

const PLUGIN_RELATIVE_PATH: &str = "frontend/scripts/governor-plugin.js";

const PLUGIN_SOURCE: &str = r#"// AUTO-GENERATED by `blast gen governor-plugin` — do not edit.
// Bridges Vite's prebuild/predev hooks to the Rust `blast check` lint engine.
import { execSync } from 'node:child_process';

export default function governorPlugin() {
  return {
    name: 'catablast-governor',
    enforce: 'pre',
    buildStart() {
      try {
        execSync('blast check', { stdio: 'inherit' });
      } catch (e) {
        throw new Error('blast check failed; see output above');
      }
    },
  };
}
"#;

/// Emit `frontend/scripts/governor-plugin.js` rooted at `project_root`.
/// Returns the absolute path of the emitted file so the caller can log it.
pub fn run(project_root: &Path) -> BlastResult<PathBuf> {
    let target = project_root.join(PLUGIN_RELATIVE_PATH);

    let parent = target
        .parent()
        .ok_or_else(|| BlastError::Invalid(format!("plugin path has no parent: {}", target.display())))?;
    fs::create_dir_all(parent)?;
    fs::write(&target, PLUGIN_SOURCE)?;

    Ok(target)
}
