use std::{
    fs,
    path::{Path, PathBuf},
};

use crate::{
    codegen::header,
    error::{BlastError, BlastResult},
    state::{AppPolicySection, FeLintState},
};

const PLUGIN_RELATIVE_PATH: &str = "frontend/scripts/governor-plugin.js";
const WHITELIST_RELATIVE_PATH: &str = ".rule_violations_whitelist";

const PLUGIN_SOURCE: &str = r#"import { execSync } from 'node:child_process';

export default function governorPlugin() {
  return {
    name: 'catablast-governor',
    enforce: 'pre',
    buildStart() {
      try {
        execSync('blast check', { stdio: 'inherit' });
      } catch (e) {
        throw new Error('blast check failed; see output above');
      }
    },
  };
}
"#;

pub fn run(project_root: &Path) -> BlastResult<Vec<PathBuf>> {
    let mut emitted = vec![write_plugin(project_root)?];
    emitted.extend(write_whitelist(project_root)?);
    Ok(emitted)
}

fn write_plugin(project_root: &Path) -> BlastResult<PathBuf> {
    let target = project_root.join(PLUGIN_RELATIVE_PATH);
    let parent = target.parent().ok_or_else(|| BlastError::Invalid(format!("plugin path has no parent: {}", target.display())))?;
    fs::create_dir_all(parent)?;
    let body = format!("{}{}", header::marker_for_app(project_root)?, PLUGIN_SOURCE);
    fs::write(&target, body)?;
    Ok(target)
}

fn fe_lint_state(project_root: &Path) -> BlastResult<FeLintState> {
    let state_dir = project_root.join("storage/blast/state");
    let app_state = match crate::state::load_app(&state_dir) {
        Ok(s) => s,
        Err(BlastError::Io(io_err)) if io_err.kind() == std::io::ErrorKind::NotFound => {
            return Ok(FeLintState::default());
        }
        Err(e) => return Err(e),
    };
    match app_state.sections.get("fe_lint") {
        Some(AppPolicySection::FeLint(state)) => Ok(state.clone()),
        Some(_non_fe_lint) => Ok(FeLintState::default()),
        None => Ok(FeLintState::default()),
    }
}

fn write_whitelist(project_root: &Path) -> BlastResult<Option<PathBuf>> {
    let state = fe_lint_state(project_root)?;
    if state.whitelist_snippets.is_empty() {
        return Ok(None);
    }
    let target = project_root.join(WHITELIST_RELATIVE_PATH);
    let mut body = String::from("# AUTO-GENERATED by `blast gen governor-plugin` — do not edit.\n");
    body.push_str("# format: <file-glob> : <optional snippet substring>\n");
    for snippet in &state.whitelist_snippets {
        body.push_str("* : ");
        body.push_str(snippet);
        body.push('\n');
    }
    fs::write(&target, body)?;
    Ok(Some(target))
}
