//! `blast gen test` — emit baseline integration test scaffolds wired to the
//! catalyst testing harness (`with_test_transaction`, `TestCtx`, `Fixture`,
//! `fixture!`). Idempotent: existing files are left untouched.

use std::fs;
use std::path::{Path, PathBuf};

use crate::codegen::ir_loader;
use crate::error::BlastResult;
use crate::state::{ResourceState, Verb};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Filter {
    All,
    Flow(String),
    Route(String),
}

#[derive(Debug, Default)]
pub struct EmitReport {
    pub written: Vec<PathBuf>,
    pub skipped: Vec<PathBuf>,
}

pub fn run(project_root: &Path, filter: &Filter) -> BlastResult<EmitReport> {
    let resources = ir_loader::load_resource_states(project_root)?;
    let mut report = EmitReport::default();

    write_once(
        &project_root.join("tests").join("common").join("mod.rs"),
        &common_mod_rs(),
        &mut report,
    )?;

    for r in &resources {
        if !filter.includes_resource(r) {
            continue;
        }

        write_once(
            &fixture_path(project_root, r.name.as_str()),
            &fixture_stub(r.name.as_str()),
            &mut report,
        )?;

        if filter.includes_routes(r) {
            write_once(
                &route_test_path(project_root, r.name.as_str()),
                &route_test_stub(r.name.as_str()),
                &mut report,
            )?;
        }

        for verb in r.verbs.keys() {
            if !filter.includes_verb(r.name.as_str(), *verb) {
                continue;
            }
            write_once(
                &flow_test_path(project_root, r.name.as_str(), *verb),
                &flow_test_stub(r.name.as_str(), *verb),
                &mut report,
            )?;
        }
    }

    write_once(
        &project_root.join("tests").join("fixtures").join("mod.rs"),
        &fixtures_mod_rs(&resources),
        &mut report,
    )?;

    Ok(report)
}

impl Filter {
    fn includes_resource(&self, r: &ResourceState) -> bool {
        match self {
            Filter::All => true,
            Filter::Flow(name) => {
                name == r.name.as_str()
                    || name.starts_with(&format!("{}/", r.name.as_str()))
            }
            Filter::Route(name) => name == r.name.as_str(),
        }
    }

    fn includes_routes(&self, r: &ResourceState) -> bool {
        match self {
            Filter::All => true,
            Filter::Route(name) => name == r.name.as_str(),
            Filter::Flow(_) => false,
        }
    }

    fn includes_verb(&self, table: &str, verb: Verb) -> bool {
        match self {
            Filter::All => true,
            Filter::Route(_) => false,
            Filter::Flow(name) => {
                let want = format!("{}/{}", table, verb_module(verb));
                name == &want || name == table
            }
        }
    }
}

fn write_once(target: &Path, body: &str, report: &mut EmitReport) -> BlastResult<()> {
    if target.exists() {
        report.skipped.push(target.to_path_buf());
        return Ok(());
    }
    let parent = target.parent().ok_or_else(|| {
        crate::error::BlastError::Invalid(format!(
            "scaffold target has no parent: {}",
            target.display()
        ))
    })?;
    fs::create_dir_all(parent)?;
    fs::write(target, body)?;
    report.written.push(target.to_path_buf());
    Ok(())
}

fn fixture_path(project_root: &Path, table: &str) -> PathBuf {
    project_root
        .join("tests")
        .join("fixtures")
        .join(format!("{}.rs", table))
}

fn route_test_path(project_root: &Path, table: &str) -> PathBuf {
    project_root
        .join("src")
        .join("transport")
        .join("http")
        .join("generated")
        .join(format!("{}.test.rs", table))
}

fn flow_test_path(project_root: &Path, table: &str, verb: Verb) -> PathBuf {
    project_root
        .join("src")
        .join("flows")
        .join("generated")
        .join(table)
        .join(format!("{}.test.rs", verb_module(verb)))
}

fn verb_module(verb: Verb) -> &'static str {
    match verb {
        Verb::List => "list",
        Verb::Get => "get",
        Verb::Create => "create",
        Verb::Update => "update",
        Verb::Delete => "delete",
    }
}

fn common_mod_rs() -> String {
    String::from(COMMON_MOD_RS)
}

const COMMON_MOD_RS: &str = r#"// AUTO-GENERATED by `blast gen test` — safe to extend.

pub use catalyst::testing::*;
pub use catalyst::fixture;

pub async fn test_pool() -> TestPool {
    use diesel_async::pooled_connection::{deadpool::Pool, AsyncDieselConnectionManager};
    use diesel_async::AsyncPgConnection;

    let url = std::env::var("DATABASE_URL_TEST")
        .expect("DATABASE_URL_TEST must be set; run via `blast test`");
    let cfg = AsyncDieselConnectionManager::<AsyncPgConnection>::new(&url);
    Pool::builder(cfg).max_size(4).build().expect("build test pool")
}
"#;

fn fixtures_mod_rs(resources: &[ResourceState]) -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by `blast gen test` — safe to extend.\n");
    let mut names: Vec<&str> = resources.iter().map(|r| r.name.as_str()).collect();
    names.sort();
    for t in names {
        out.push_str(&format!("pub mod {};\n", t));
    }
    out
}

fn fixture_stub(table: &str) -> String {
    let singular = singularize(table);
    let type_name = pascal_case(&singular);
    FIXTURE_TEMPLATE
        .replace("__TABLE__", table)
        .replace("__TYPE__", &type_name)
}

const FIXTURE_TEMPLATE: &str = r#"// AUTO-GENERATED by `blast gen test` — fill in the body, then own this file.

use catalyst::meltdown::MeltDown;
use catalyst::testing::{Fixture, TestCtx};

use crate::structs::generated::__TABLE__::__TYPE__;

impl Fixture for __TYPE__ {
    async fn create(_ctx: &mut TestCtx<'_>) -> Result<Self, MeltDown> {
        panic!("populate __TYPE__ fixture via flows::__TABLE__::create::run")
    }
}
"#;

fn flow_test_stub(table: &str, verb: Verb) -> String {
    let verb_str = verb_module(verb);
    let singular = singularize(table);
    let type_name = pascal_case(&singular);

    let body = match verb {
        Verb::Create => CREATE_BODY.to_string(),
        Verb::List => LIST_BODY.replace("__TYPE__", &type_name),
        Verb::Get => GET_BODY.replace("__TYPE__", &type_name),
        Verb::Update => UPDATE_BODY.replace("__TYPE__", &type_name),
        Verb::Delete => DELETE_BODY.replace("__TYPE__", &type_name),
    };

    FLOW_TEMPLATE
        .replace("__TABLE__", table)
        .replace("__VERB__", verb_str)
        .replace("__TYPE__", &type_name)
        .replace("__BODY__", &body)
}

const FLOW_TEMPLATE: &str = r#"// AUTO-GENERATED by `blast gen test` — fill in assertions, then own this file.

#[cfg(test)]
mod tests {
    use catalyst::meltdown::MeltDown;
    use catalyst::testing::run_in_test;
    #[allow(unused_imports)]
    use catalyst::fixture;

    #[allow(unused_imports)]
    use crate::structs::generated::__TABLE__::__TYPE__;
    use crate::tests_common::test_pool;

    #[tokio::test]
    async fn __VERB___baseline() {
        let pool = test_pool().await;
        run_in_test(&pool, |b| b, |ctx| Box::pin(async move {
__BODY__        }))
            .await
            .expect("__VERB___baseline rolled back cleanly");
    }
}
"#;

const CREATE_BODY: &str = r#"            Ok::<(), MeltDown>(())
"#;

const LIST_BODY: &str = r#"            fixture!(let _seed: __TYPE__ = ctx);
            Ok::<(), MeltDown>(())
"#;

const GET_BODY: &str = r#"            fixture!(let row: __TYPE__ = ctx);
            assert!(row.id == row.id);
            Ok::<(), MeltDown>(())
"#;

const UPDATE_BODY: &str = r#"            fixture!(let row: __TYPE__ = ctx);
            assert!(row.id == row.id);
            Ok::<(), MeltDown>(())
"#;

const DELETE_BODY: &str = r#"            fixture!(let row: __TYPE__ = ctx);
            assert!(row.id == row.id);
            Ok::<(), MeltDown>(())
"#;

fn route_test_stub(table: &str) -> String {
    ROUTE_TEMPLATE.replace("__TABLE__", table)
}

const ROUTE_TEMPLATE: &str = r#"// AUTO-GENERATED by `blast gen test` — fill in assertions, then own this file.

#[cfg(test)]
mod tests {
    use axum::body::Body;
    use axum::http::{Request, StatusCode};
    use catalyst::meltdown::MeltDown;
    use catalyst::testing::run_in_test;
    use tower::ServiceExt;

    use crate::tests_common::test_pool;
    use crate::transport::http::generated::__TABLE__ as route_mod;

    #[tokio::test]
    async fn __TABLE___routes_smoke() {
        let pool = test_pool().await;
        run_in_test(&pool, |b| b, |ctx| Box::pin(async move {
            let app = route_mod::routes();
            let response = app
                .oneshot(
                    Request::builder()
                        .uri("/api/__TABLE__")
                        .body(Body::empty())
                        .expect("build request"),
                )
                .await
                .expect("oneshot succeeds");
            assert!(
                response.status() != StatusCode::INTERNAL_SERVER_ERROR,
                "baseline route hit returned 500"
            );
            let _ctx = ctx;
            Ok::<(), MeltDown>(())
        }))
        .await
        .expect("__TABLE___routes_smoke rolled back cleanly");
    }
}
"#;

fn singularize(table: &str) -> String {
    for suffix in ["sses", "shes", "ches", "xes", "zes"] {
        match table.strip_suffix(suffix) {
            Some(stem) => return format!("{}{}", stem, &suffix[..suffix.len() - 2]),
            None => continue,
        }
    }
    match table.strip_suffix("ies") {
        Some(stem) => format!("{}y", stem),
        None => match table.strip_suffix('s') {
            Some(stem) => stem.to_string(),
            None => table.to_string(),
        },
    }
}

fn pascal_case(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    let mut upper_next = true;
    for ch in input.chars() {
        if ch == '_' || ch == '-' {
            upper_next = true;
            continue;
        }
        if upper_next {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
mod unit {
    use super::*;

    #[test]
    fn singularize_handles_common_endings() {
        assert_eq!(singularize("users"), "user");
        assert_eq!(singularize("addresses"), "address");
        assert_eq!(singularize("companies"), "company");
        assert_eq!(singularize("boxes"), "box");
        assert_eq!(singularize("media"), "media");
    }

    #[test]
    fn pascal_case_handles_snake() {
        assert_eq!(pascal_case("user"), "User");
        assert_eq!(pascal_case("user_account"), "UserAccount");
        assert_eq!(pascal_case("two_factor_auth"), "TwoFactorAuth");
    }
}
