//! Orchestration + file I/O for `blast gen structs` (v2 emitter).
//!
//! For every resource state file under `storage/blast/state/resources/`:
//!   1. emit `<project_root>/src/structs/generated/<table>.rs` carrying the per-variant projection structs (see `emitter.rs`)
//!   2. maintain a barrel `mod.rs` next to the per-resource files
//!
//! Every emitted file is prepended with a state-hash marker so the user
//! app's `build.rs` will refuse to compile if the on-disk state changed
//! since the last `blast gen all`.

use std::{
    fs,
    path::{Path, PathBuf},
};

use crate::{
    codegen::{header, ir_loader, structs::emitter},
    error::{BlastError, BlastResult},
    io::traits::{Progress, ProgressExt, Sink, SinkExt},
    state::ResourceState,
};

#[derive(Debug, Default)]
pub struct EmitReport {
    pub written: Vec<PathBuf>,
    pub skipped: Vec<PathBuf>,
}

const STEP_LABEL: &str = "structs: emit per-resource projections";

pub fn run(project_root: &Path, sink: &mut dyn Sink, progress: &mut dyn Progress) -> BlastResult<EmitReport> {
    progress.step_start(STEP_LABEL);

    let resources = match ir_loader::load_resource_states(project_root) {
        Ok(rs) => rs,
        Err(err) => {
            let reason = err.to_string();
            progress.step_fail(STEP_LABEL, &reason);
            sink.error(format!("{STEP_LABEL}: {reason}"));
            return Err(err);
        }
    };

    let mut report = EmitReport::default();

    if resources.is_empty() {
        sink.info(format!("{STEP_LABEL}: no resources declared; nothing to emit"));
        progress.step_done(STEP_LABEL);
        return Ok(report);
    }

    let out_dir = generated_dir(project_root);
    fs::create_dir_all(&out_dir)?;

    let total = resources.len() as u64;
    for (idx, resource) in resources.iter().enumerate() {
        emit_resource(project_root, resource, &out_dir, &mut report)?;
        sink.info(format!("structs: emitted {}", resource_target(&out_dir, resource).display()));
        progress.tick(idx as u64 + 1, total);
    }

    let barrel_target = out_dir.join("mod.rs");
    let barrel_marker = header::marker_for_app(project_root)?;
    let barrel_body = format!("{}{}", barrel_marker, render_barrel(&resources));
    write_file(&barrel_target, &barrel_body, &mut report)?;
    sink.info(format!("structs: emitted {}", barrel_target.display()));

    progress.step_done(STEP_LABEL);
    Ok(report)
}

fn emit_resource(project_root: &Path, resource: &ResourceState, out_dir: &Path, report: &mut EmitReport) -> BlastResult<()> {
    let target = resource_target(out_dir, resource);
    let marker = header::marker_for_resource(project_root, resource.name.as_str())?;
    let body = format!("{}{}", marker, emitter::render_resource_body(resource));
    write_file(&target, &body, report)
}

fn resource_target(out_dir: &Path, resource: &ResourceState) -> PathBuf {
    out_dir.join(format!("{}.rs", resource.name.as_str()))
}

fn generated_dir(project_root: &Path) -> PathBuf {
    project_root.join("src").join("structs").join("generated")
}

fn write_file(target: &Path, body: &str, report: &mut EmitReport) -> BlastResult<()> {
    let parent = target.parent().ok_or_else(|| BlastError::Invalid(format!("structs target has no parent: {}", target.display())))?;
    fs::create_dir_all(parent)?;
    fs::write(target, body)?;
    report.written.push(target.to_path_buf());
    Ok(())
}

fn render_barrel(resources: &[ResourceState]) -> String {
    let mut names: Vec<&str> = resources.iter().map(|r| r.name.as_str()).collect();
    names.sort();

    let mut out = String::new();
    out.push_str("//! Per-resource projection-struct modules. Generated by Blast.\n\n");
    for name in &names {
        out.push_str(&format!("pub mod {name};\n"));
    }
    out
}

#[cfg(test)]
mod tests {
    use std::collections::{BTreeMap, BTreeSet};

    use indexmap::IndexMap;
    use tempfile::TempDir;

    use super::*;
    use crate::{
        io::null::{NullProgress, NullSink},
        state::{names::ResourceName, AuthMode, FieldName, FieldState, FieldVariant, FilterKind, ListOptions, SqlType, Verb, VerbState},
    };

    fn variants(items: &[FieldVariant]) -> BTreeSet<FieldVariant> {
        items.iter().copied().collect()
    }

    fn write_full_resource(project_root: &Path, table: &str) -> BlastResult<()> {
        let mut fields: IndexMap<FieldName, FieldState> = IndexMap::new();
        fields.insert(
            FieldName::new("id"),
            FieldState {
                sql_type: SqlType::new("Int8"),
                variants: variants(&[FieldVariant::Db, FieldVariant::Public, FieldVariant::Admin]),
                nullable: false,
                primary_key: true,
                validators: BTreeSet::new(),
            },
        );
        fields.insert(
            FieldName::new("email"),
            FieldState {
                sql_type: SqlType::new("Varchar"),
                variants: variants(&[FieldVariant::Db, FieldVariant::Insertable, FieldVariant::Patch, FieldVariant::Public, FieldVariant::Admin]),
                nullable: false,
                primary_key: false,
                validators: BTreeSet::new(),
            },
        );

        let mut filterable: BTreeMap<FieldName, FilterKind> = BTreeMap::new();
        filterable.insert(FieldName::new("email"), FilterKind::Eq);
        let mut verbs: IndexMap<Verb, VerbState> = IndexMap::new();
        verbs.insert(
            Verb::List,
            VerbState {
                auth: AuthMode::Public,
                list_options: Some(ListOptions {
                    paginated: true,
                    filterable_columns: filterable,
                    sortable_columns: BTreeSet::new(),
                    default_sort: None,
                    max_page_size: Some(100),
                }),
            },
        );

        let mut resource = ResourceState::new(ResourceName::new(table));
        resource.fields = fields;
        resource.verbs = verbs;

        let state_dir = project_root.join("storage").join("blast").join("state");
        crate::state::save_resource(&state_dir, &resource)?;

        let app = crate::state::AppState::default();
        crate::state::io::save_app(&state_dir, &app)?;
        Ok(())
    }

    #[test]
    fn emits_per_resource_file_and_barrel_with_markers() {
        let tmp = TempDir::new().expect("tempdir");
        let root = tmp.path();
        write_full_resource(root, "users").expect("write resource state");

        let mut sink = NullSink;
        let mut progress = NullProgress;
        let report = run(root, &mut sink, &mut progress).expect("structs codegen ok");

        let target = root.join("src/structs/generated/users.rs");
        let barrel = root.join("src/structs/generated/mod.rs");
        assert!(target.exists(), "per-resource file missing");
        assert!(barrel.exists(), "barrel mod.rs missing");
        assert!(report.written.contains(&target));
        assert!(report.written.contains(&barrel));

        let body = fs::read_to_string(&target).expect("read body");
        assert!(body.starts_with("// AUTO-GENERATED from "), "missing marker header in {}", target.display(),);
        assert!(body.contains("storage/blast/state/resources/users.ron"), "marker should reference state path",);
        assert!(body.contains("pub struct User {"));
        assert!(body.contains("pub struct UserInsertable {"));
        assert!(body.contains("pub struct UserPatch {"));
        assert!(body.contains("pub struct UserPublic {"));
        assert!(body.contains("pub struct UserAdmin {"));
        assert!(body.contains("pub struct UserFilter {"));

        let barrel_body = fs::read_to_string(&barrel).expect("read barrel");
        assert!(barrel_body.contains("pub mod users;"));
        assert!(barrel_body.starts_with("// AUTO-GENERATED from "), "barrel missing marker header",);
    }

    #[test]
    fn empty_state_emits_nothing() {
        let tmp = TempDir::new().expect("tempdir");
        let root = tmp.path();
        fs::create_dir_all(root.join("storage/blast/state/resources")).expect("mkdir state");

        let mut sink = NullSink;
        let mut progress = NullProgress;
        let report = run(root, &mut sink, &mut progress).expect("structs codegen on empty");
        assert!(report.written.is_empty());
        assert!(!root.join("src/structs/generated").exists());
    }

    #[test]
    fn barrel_lists_resources_in_lexical_order() {
        let tmp = TempDir::new().expect("tempdir");
        let root = tmp.path();
        write_full_resource(root, "zebras").expect("zebras");
        write_full_resource(root, "apples").expect("apples");

        let mut sink = NullSink;
        let mut progress = NullProgress;
        run(root, &mut sink, &mut progress).expect("structs codegen ok");

        let barrel = fs::read_to_string(root.join("src/structs/generated/mod.rs")).expect("read barrel");
        let apples_idx = barrel.find("pub mod apples;").expect("apples present");
        let zebras_idx = barrel.find("pub mod zebras;").expect("zebras present");
        assert!(apples_idx < zebras_idx, "barrel must be lexical");
    }
}
