//! Session-layer traits decoupling catalyst from any concrete `User` table.
//!
//! User-apps implement these (by hand or via Blast codegen) so catalyst's
//! session middleware can look up a user from a token, mint new tokens, and
//! revoke them — without ever knowing the user-app's row shape.

use diesel_async::AsyncPgConnection;

use crate::meltdown::MeltDown;

/// Implemented by the user-app's `User` struct so catalyst session machinery
/// can interrogate identity + role without depending on the concrete type.
///
/// `id()` returns `i64` for forward-compat with apps that prefer wider PKs;
/// the framework-side [`SessionContext`](super::SessionContext) currently
/// stores `i32` and casts on construction.
pub trait SessionUser: Clone + Send + Sync + 'static {
    fn id(&self) -> i64;
    fn role(&self) -> &str;

    fn is_admin(&self) -> bool {
        self.role() == "admin"
    }

    fn has_role(&self, role: &str) -> bool {
        self.role() == role
    }
}

/// Implemented by the user-app's auth layer (or generated by Blast) to teach
/// catalyst how to resolve a session token into a user, plus how to mint and
/// revoke tokens.
///
/// All methods take a borrowed `&mut AsyncPgConnection` so the caller controls
/// pooling/transaction scope.
#[async_trait::async_trait]
pub trait SessionAdapter: Send + Sync + 'static {
    type User: SessionUser;

    /// Lookup the user associated with a valid session token.
    ///
    /// Returns `Ok(None)` when the token is unknown, revoked, or expired.
    /// Returns `Err(_)` only on infrastructure failures (DB down, etc.).
    async fn user_from_token(
        &self,
        conn: &mut AsyncPgConnection,
        token: &str,
    ) -> Result<Option<Self::User>, MeltDown>;

    /// Create a new session token for a user (login flow).
    ///
    /// Returns the opaque bearer token to hand back to the client.
    async fn create_session(
        &self,
        conn: &mut AsyncPgConnection,
        user_id: i64,
    ) -> Result<String, MeltDown>;

    /// Invalidate a session token (logout flow).
    async fn revoke_session(
        &self,
        conn: &mut AsyncPgConnection,
        token: &str,
    ) -> Result<(), MeltDown>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::meltdown::{MeltDown, MeltType};

    /// Dummy user struct standing in for a user-app's generated User row.
    #[derive(Clone)]
    struct DummyUser {
        id: i64,
        role: String,
    }

    impl SessionUser for DummyUser {
        fn id(&self) -> i64 {
            self.id
        }
        fn role(&self) -> &str {
            &self.role
        }
    }

    /// Dummy adapter that doesn't touch a real connection — just verifies the
    /// trait can be implemented + invoked in a sane shape.
    struct DummyAdapter;

    #[async_trait::async_trait]
    impl SessionAdapter for DummyAdapter {
        type User = DummyUser;

        async fn user_from_token(
            &self,
            _conn: &mut AsyncPgConnection,
            token: &str,
        ) -> Result<Option<Self::User>, MeltDown> {
            if token == "valid" {
                Ok(Some(DummyUser { id: 42, role: "admin".to_string() }))
            } else {
                Ok(None)
            }
        }

        async fn create_session(
            &self,
            _conn: &mut AsyncPgConnection,
            _user_id: i64,
        ) -> Result<String, MeltDown> {
            Ok("dummy-token".to_string())
        }

        async fn revoke_session(
            &self,
            _conn: &mut AsyncPgConnection,
            _token: &str,
        ) -> Result<(), MeltDown> {
            Err(MeltDown::new(MeltType::Unexpected("dummy".into()), "no-op"))
        }
    }

    #[test]
    fn session_user_default_role_helpers() {
        let admin = DummyUser { id: 1, role: "admin".to_string() };
        let plain = DummyUser { id: 2, role: "user".to_string() };

        assert!(admin.is_admin());
        assert!(!plain.is_admin());

        assert!(admin.has_role("admin"));
        assert!(plain.has_role("user"));
        assert!(!plain.has_role("admin"));

        assert_eq!(admin.id(), 1);
        assert_eq!(plain.role(), "user");
    }

    #[test]
    fn session_adapter_object_safety_via_static_dispatch() {
        // Compile-time guarantee that a SessionAdapter impl exists and its
        // associated User type implements SessionUser. This is the
        // "traits can be implemented on a dummy struct" acceptance check.
        fn assert_impls<A: SessionAdapter>() {}
        assert_impls::<DummyAdapter>();
    }

    #[test]
    fn session_context_from_user_extracts_primitives() {
        use crate::sessions::SessionContext;

        let user = DummyUser { id: 7, role: "editor".to_string() };
        let ctx = SessionContext::from_user(99, &user);

        assert_eq!(ctx.session_id, 99);
        assert_eq!(ctx.user_id, 7);
        assert_eq!(ctx.role, "editor");
        assert!(ctx.has_role("editor"));
        assert!(!ctx.is_admin());
    }
}
