use crate::state::Verb;

pub fn verb_module(verb: Verb) -> &'static str {
    match verb {
        Verb::List => "list",
        Verb::Get => "get",
        Verb::Create => "create",
        Verb::Update => "update",
        Verb::Delete => "delete",
    }
}

pub fn render_verb_body(table: &str, verb: Verb) -> String {
    let singular = singularize(table);
    let stem = pascal_case(&singular);
    let insertable = format!("{stem}Insertable");
    let patch = format!("{stem}Patch");
    let public = format!("{stem}Public");

    match verb {
        Verb::List => format!(
            r#"use crate::structs::generated::{table}::{public};
use crate::Ctx;

pub async fn run(
    ctx: &Ctx,
    query: crate::structs::list_query::ListQuery,
) -> ::std::result::Result<
    crate::structs::list_query::ListResponse<{public}>,
    crate::meltdown::MeltDown,
> {{
    let mut conn = ctx.conn().await?;
    let out = crate::models::generated::{table}::list(&mut conn, &query).await?;
    Ok(out.map(|row| row.into()))
}}
"#
        ),
        Verb::Get => format!(
            r#"use crate::structs::generated::{table}::{public};
use crate::Ctx;

pub async fn run(
    ctx: &Ctx,
    id: i64,
) -> ::std::result::Result<{public}, crate::meltdown::MeltDown> {{
    let mut conn = ctx.conn().await?;
    let out = crate::models::generated::{table}::get(&mut conn, id).await?;
    Ok(out.into())
}}
"#
        ),
        Verb::Create => format!(
            r#"use crate::structs::generated::{table}::{{{insertable}, {public}}};
use crate::Ctx;

pub async fn run(
    ctx: &Ctx,
    input: {insertable},
) -> ::std::result::Result<{public}, crate::meltdown::MeltDown> {{
    let mut conn = ctx.conn().await?;
    let out = crate::models::generated::{table}::create(&mut conn, &input).await?;
    Ok(out.into())
}}
"#
        ),
        Verb::Update => format!(
            r#"use crate::structs::generated::{table}::{{{patch}, {public}}};
use crate::Ctx;

pub async fn run(
    ctx: &Ctx,
    id: i64,
    patch: {patch},
) -> ::std::result::Result<{public}, crate::meltdown::MeltDown> {{
    let mut conn = ctx.conn().await?;
    let out = crate::models::generated::{table}::update(&mut conn, id, &patch).await?;
    Ok(out.into())
}}
"#
        ),
        Verb::Delete => format!(
            r#"use crate::Ctx;

pub async fn run(
    ctx: &Ctx,
    id: i64,
) -> ::std::result::Result<(), crate::meltdown::MeltDown> {{
    let mut conn = ctx.conn().await?;
    crate::models::generated::{table}::delete(&mut conn, id).await?;
    Ok(())
}}
"#
        ),
    }
}

pub fn render_resource_barrel(verbs: &[Verb]) -> String {
    let mut out = String::new();
    out.push_str("//! Per-verb routine modules for this resource. Generated by Blast.\n\n");
    for verb in verbs {
        out.push_str(&format!("pub mod {};\n", verb_module(*verb)));
    }
    out
}

pub fn render_top_barrel(tables: &[&str]) -> String {
    let mut sorted: Vec<&str> = tables.to_vec();
    sorted.sort();
    let mut out = String::new();
    out.push_str("//! Per-resource routine subdirectories. Generated by Blast.\n\n");
    for t in sorted {
        out.push_str(&format!("pub mod {t};\n"));
    }
    out
}

fn singularize(table: &str) -> String {
    for suffix in ["sses", "shes", "ches", "xes", "zes"] {
        match table.strip_suffix(suffix) {
            Some(stem) => return format!("{}{}", stem, &suffix[..suffix.len() - 2]),
            None => continue,
        }
    }
    match table.strip_suffix("ies") {
        Some(stem) => format!("{}y", stem),
        None => match table.strip_suffix('s') {
            Some(stem) => stem.to_string(),
            None => table.to_string(),
        },
    }
}

fn pascal_case(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    let mut upper_next = true;
    for ch in input.chars() {
        if ch == '_' || ch == '-' {
            upper_next = true;
            continue;
        }
        if upper_next {
            for u in ch.to_uppercase() {
                out.push(u);
            }
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn list_emits_map_into_public() {
        let body = render_verb_body("users", Verb::List);
        assert!(body.contains("ListResponse<UserPublic>"));
        assert!(body.contains("crate::models::generated::users::list(&mut conn, &query)"));
        assert!(body.contains("Ok(out.map(|row| row.into()))"));
    }

    #[test]
    fn get_returns_public_dto() {
        let body = render_verb_body("users", Verb::Get);
        assert!(body.contains("Result<UserPublic, crate::meltdown::MeltDown>"));
        assert!(body.contains("crate::models::generated::users::get(&mut conn, id)"));
    }

    #[test]
    fn create_takes_owned_insertable() {
        let body = render_verb_body("users", Verb::Create);
        assert!(body.contains("input: UserInsertable"));
        assert!(body.contains("crate::models::generated::users::create(&mut conn, &input)"));
    }

    #[test]
    fn update_takes_owned_patch() {
        let body = render_verb_body("users", Verb::Update);
        assert!(body.contains("patch: UserPatch"));
        assert!(body.contains("crate::models::generated::users::update(&mut conn, id, &patch)"));
    }

    #[test]
    fn delete_returns_unit() {
        let body = render_verb_body("users", Verb::Delete);
        assert!(body.contains("Result<(), crate::meltdown::MeltDown>"));
        assert!(body.contains("crate::models::generated::users::delete(&mut conn, id)"));
    }

    #[test]
    fn singularize_handles_common_plurals() {
        assert_eq!(singularize("users"), "user");
        assert_eq!(singularize("posts"), "post");
        assert_eq!(singularize("companies"), "company");
        assert_eq!(singularize("addresses"), "address");
    }

    #[test]
    fn pascal_case_handles_snake() {
        assert_eq!(pascal_case("user_role"), "UserRole");
        assert_eq!(pascal_case("blog_post"), "BlogPost");
    }

    #[test]
    fn top_barrel_sorted() {
        let body = render_top_barrel(&["zebras", "apples", "users"]);
        let a = body.find("pub mod apples;").expect("apples");
        let u = body.find("pub mod users;").expect("users");
        let z = body.find("pub mod zebras;").expect("zebras");
        assert!(a < u && u < z);
    }
}
